apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llm-server
  name: llm-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      containers:
      - name: llm-server
        image: llm-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
